### ISSUE TITLE
exptool check:status throwing "SERVER_ERROR"

### ISSUE THREAD

**Issue by ponswaminathanr** [mglagola/exptool#3]
Need some suggestion
running exptool check:status throwing  the following error 

$ exptool check:status
500 - {"err":"This experience is missing a name and cannot be published.","apiError":false,"code":"SERVER_ERROR"}
StatusCodeError: 500 - {"err":"This experience is missing a name and cannot be published.","apiError":false,"code":"SERVER_ERROR"}
    at new StatusCodeError (/Users/pramasamy/.nvm/versions/node/v8.9.4/lib/node_modules/exptool/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/pramasamy/.nvm/versions/node/v8.9.4/lib/node_modules/exptool/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/pramasamy/.nvm/versions/node/v8.9.4/lib/node_modules/exptool/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/pramasamy/.nvm/versions/node/v8.9.4/lib/node_modules/exptool/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/pramasamy/.nvm/versions/node/v8.9.4/lib/node_modules/exptool/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/pramasamy/.nvm/versions/node/v8.9.4/lib/node_modules/exptool/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by mglagola** [comment]
@ponswaminathanr Thanks for pointing this out. I'm pretty sure I know what caused this. Try upgrading to exptool@0.4.8 to see if that solves your issue.
